---
# Ansible playbook that generates the TLS keys and certificates used by the
# cluster.

- hosts: 127.0.0.1
  connection: local
  vars_files:
  - ../openstack_vars.yml
  roles:
    - cluster_certs
    - web_certs
