---
# Ansible playbook that generates the TLS keys and certificates used by the
# cluster.

- hosts: localhost
  connection: local
  vars_files:
  - ../openstack_vars.yml
  roles:
    - cluster_certs
    - web_certs
