---
# Ansible playbook that generates the TLS keys and certificates used by the
# cluster.

- hosts: localhost
  connection: local
  vars_files:
  - ../openstack_vars.yml
  roles:
    - gen_certs_cluster
    - gen_certs_web
