sudo: required
dist: trusty
language: ruby
cache: bundler
addons:
  postgresql: "9.6"
services:
  - postgresql
before_script:
  - npm install bower
  - RAILS_ENV=test bin/bundle exec rake db:create db:migrate
  - RAILS_ENV=production bin/bundle exec rake assets:precompile
script: bin/rails test test/models test/controllers test/helpers
                       test/mailers test/jobs
rvm:
  - "2.4.1"
