---
- name: create certbot non-confidential directories
  become: true
  become_user: "{{ app_user }}"
  file: path=/home/{{ app_user }}/{{ item }} state=directory mode=0755
  with_items:
  - "{{ app_certs_dir }}"
  - "{{ app_certs_www_dir }}"

- name: create certbot confidential directories
  become: true
  become_user: "{{ app_user }}"
  file: path=/home/{{ app_user }}/{{ item }} state=directory mode=0750
  with_items:
  - "{{ app_certs_config_dir }}"
  - "{{ app_certs_logs_dir }}"
  - "{{ app_certs_work_dir }}"
