---
- include: config.yml
- include: files.yml
- include: deps.yml
- include: systemd.yml
- include: bootstrap.yml
- include: surrogate.yml

- name: enable and start systemd units for certificate update timer
  become: true
  become_user: root
  service: name={{ app_certbot_service }}.timer enabled=yes state=started
