---
delayed_job: 
  :binary: script/delayed_job
  :absolute_binary: false
  # The File.read expression computes the number of CPU cores in the system.
  :start_args: --prefix <%= Rails.root %> -n <%= [3, File.read("/proc/cpuinfo").scan(/^processor\s*:/).length - 1].min %> start
  :stop_args: stop
  # Pattern for the PID file(s) used by the daemon.
  :pids: tmp/pids/delayed_job.*.pid
  # Override for the patterns used to identify the daemon's processes.
  :kill_patterns: <%= Rails.root.join 'delayed_job' %>
  # Time to wait after sending the stop command, before killing the daemon.
  :delay_before_kill: 0.2
  # Override the daemon startup order. Starling consumer daemons should have
  # their start_order set to 2, so starling is running when they start.
  :start_order: 1
  # daemonz will ignore this daemon configuration when this flag is true
  :disabled: false
