<% starling_port = (/staging/ =~ Rails.env.to_s) ? 16030 : 16020 %>
<% 1.upto(Rails.env.production? ? 4 : 2) do |i| %>
  starling_consumer_<%= i %>:
    :pids: tmp/consumer_<%= i %>/StarlingConsumer.pid
    :binary: script/background/starling_consumer.rb
    :start_args: start <%= Rails.env %> 127.0.0.1:<%= starling_port %> <%= Rails.root %>/tmp/consumer_<%= i %>
    :stop_args: stop <%= Rails.env %> 127.0.0.1:<%= starling_port %> <%= Rails.root %>/tmp/consumer_<%= i %>
    :kill_patterns: <%= Rails.root %>/tmp/consumer_<%= i %>
    :delay_before_kill: 0.3
    :disabled: false
    :start_order: 2
<% end %>
