<% starling_port = (RAILS_ROOT =~ /staging/ ? 16030 : 16020) %>
<% 1.upto(RAILS_ENV == 'production' ? 4 : 2) do |i| %>
  starling_consumer_<%= i %>:
    :pids: tmp/consumer_<%= i %>/StarlingConsumer.pid
    :binary: script/background/starling_consumer.rb
    :start_args: start <%= RAILS_ENV %> 127.0.0.1:<%= starling_port %> <%= RAILS_ROOT %>/tmp/consumer_<%= i %>
    :stop_args: stop <%= RAILS_ENV %> 127.0.0.1:<%= starling_port %> <%= RAILS_ROOT %>/tmp/consumer_<%= i %>
    :kill_patterns: <%= RAILS_ROOT %>/tmp/consumer_<%= i %>
    :delay_before_kill: 0.3
    :disabled: false
    :start_order: 2
<% end %>
