---
# The interface used to connect to other computers in the cluster.
#
# This is generally eth0. Currently, only Vagrant VMs are special-cased.
cluster_net_interface: "{{ 'eth1' if ansible_ssh_user == 'vagrant'
                           else 'eth0' }}"
