---
# Sets up a skydns server reading from the local etcd.

- name: install skydns with dnf
  when: ansible_pkg_mgr == 'dnf'
  become: true
  become_user: root
  dnf: name=skydns state=present

- name: install skydns with apt
  when: ansible_pkg_mgr == 'apt'
  become: true
  become_user: root
  apt: name=skydns state=present

- include: etcd_tls_keys.yml
- include: etcd_config.yml

- name: write skydns config
  become: true
  become_user: root
  template: src=skydns.conf.j2 dest=/etc/skydns/skydns.conf
  notify:
  - restart skydns server

# TODO(pwnall): Remove this hack when the bug below gets fixed.
#               https://bugzilla.redhat.com/show_bug.cgi?id=1366968
- name: set SELinux to permissive
  when: ansible_selinux != False
  become: true
  become_user: root
  selinux: policy=targeted state=permissive

- name: enable and start skydns systemd socket
  become: true
  become_user: root
  service: name=skydns.socket enabled=yes state=started

- name: enable and start skydns systemd service
  become: true
  become_user: root
  service: name=skydns.service enabled=yes state=started

- name: open dns service in firewalld
  when: has_firewalld != False
  become: true
  become_user: root
  firewalld: port={{ item }} state=enabled immediate=yes permanent=yes
  with_items:
  - "53/tcp"
  - "53/udp"

# NOTE: Other roles rely on skydns being up and configured correctly.
- meta: flush_handlers
