---
# The name of the frontend application.
#
# This is used to derive several of the properties below.
app_name: igor

# The name of the user account that contains the frontend application.
app_user: "{{ app_name }}_web"

# The name of the Systemd service that updates the application's certificate.
app_certbot_service: "{{ app_name }}_cert"

# The name of the Systemd service used to bootstrap certbot.
app_certbot_bootstrap_service: "{{ app_name }}_cert_bootstrap"

# The directory that holds all the certbot data.
# This is a relative path inside the user's home directory.
app_certs_dir: "certs"

# The directory that holds the certbot certificates.
# This is a relative path inside the user's home directory.
app_certs_config_dir: "{{ app_certs_dir }}/config"

# The directory that holds the certbot logs.
# This is a relative path inside the user's home directory.
app_certs_logs_dir: "{{ app_certs_dir }}/logs"

# The directory that holds the certbot bootstrap wwwroot.
# This is a relative path inside the user's home directory.
app_certs_www_dir: "{{ app_certs_dir }}/wwwroot"

# The directory that holds certbot's temporary files.
# This is a relative path inside the user's home directory.
app_certs_work_dir: "{{ app_certs_dir }}/work-dir"

# HACK(pwnall): these should be read from a file
app_certs_email: "victor@costan.us"
