---
- name: restart nginx daemon
  become: true
  become_user: root
  service: name=nginx state=restarted

- name: reload systemd configuration
  command: systemctl daemon-reload
  become: true
  become_user: root

- name: restart frontend main service
  become: true
  become_user: root
  service: name={{ app_main_service }} state=restarted

- name: restart frontend job queue service
  become: true
  become_user: root
  service: name={{ app_queue_service }} state=restarted
