---
- name: install ruby and packages needed to compile ruby gems
  become: true
  become_user: root
  dnf: name={{ item }} state=present
  with_items:
  - ruby
  - ruby-devel
  - gcc
  - gcc-c++
  - make
  - automake
  - autoconf
  - curl-devel
  - openssl-devel
  - zlib-devel
  - patch
  - git
