---
# Installs the packages that make up a good build environment for Ruby gems.
#
# The Package list is sourced from the lists below and from experience.
#     https://github.com/rbenv/ruby-build/wiki
#     https://github.com/postmodern/chruby/wiki/Ruby

- name: install ruby and dnf packages needed to compile ruby gems
  when: ansible_pkg_mgr == 'dnf'
  become: true
  become_user: root
  dnf: name={{ item }} state=present
  with_items:
  - ruby
  - ruby-devel
  - automake
  - autoconf
  - bison
  - bzip2
  - curl-devel
  - flex
  - gcc
  - gcc-c++
  - gdm-devel
  - git
  - java-1.8.0-openjdk
  - libffi-devel
  - libyaml-devel
  - llvm-devel
  - llvm-static
  - make
  - ncurses-devel
  - openssl-devel
  - readline-devel
  - redhat-rpm-config
  - patch
  - which
  - zlib-devel

- name: install ruby and apt packages needed to compile ruby gems
  when: ansible_pkg_mgr == 'apt'
  become: true
  become_user: root
  apt: name={{ item }} state=present
  with_items:
  - ruby
  - ruby-dev
  - autoconf
  - automake
  - bison
  - build-essential
  - flex
  - gcc
  - g++
  - git-core
  - libcurl4-openssl-dev
  - libffi-dev
  - libgdm-dev
  - libncurses5-dev
  - libreadline6-dev
  - libssl-dev
  - libyaml-devl
  - llvm-dev
  - openjdk-8-jdk
  - patch
  - zlib1g-dev
