---
# Sets generally useful facts.

# NOTE: This probably belongs in Ansible, but it will not get added there.
#       https://github.com/ansible/ansible/pull/12288
- name: look for firewalld
  stat: path=/usr/bin/firewall-cmd
  register: firewall_cmd_stat
- name: set has_firewalld fact
  set_fact:
    has_firewalld: "{{ firewall_cmd_stat.stat.exists }}"

- name: set root_fs_type fact
  set_fact:
    root_fs_type: "{{
        (ansible_mounts | selectattr('mount', 'equalto', '/') | first).fstype
        }}"
