---
- include: packages.yml
- include: docker.yml

- name: check out repository
  become: true
  become_user: "{{ app_user }}"
  git:
    recursive: yes
    repo: "{{ app_git_repo }}"
    version: "{{ app_git_branch }}"
    dest: /home/{{ app_user }}/{{ app_dir }}
    update: yes
    force: yes
  notify:
  - restart frontend main service
  - restart frontend job queue service

# TODO(pwnall): everything except for foreman and rake should be in the
#               ruby_bundler task
- name: install or update core gems
  become: true
  become_user: "{{ app_user }}"
  gem: name={{ item }} state=latest
  with_items:
  - bigdecimal  # Default gem, missing for some reason in Fedora 25.
  - bundler
  - foreman
  - io-console  # Default gem, missing for some reason in Fedora 25.
  - rake

- name: install npm packages
  become: true
  become_user: "{{ app_user }}"
  npm:
    path: /home/{{ app_user }}/{{ app_dir }}
    state: present
    production: yes

- name: install bundler packages
  become: true
  become_user: "{{ app_user }}"
  bundler:
    executable: /home/{{ app_user }}/{{ app_dir }}/bin/bundle
    chdir: /home/{{ app_user }}/{{ app_dir }}
    clean: yes
    deployment_mode: yes
    state: present
    user_install: yes
    exclude_groups:
    - development
    - test

- name: precompile assets
  become: true
  become_user: "{{ app_user }}"
  command: /home/{{ app_user }}/{{ app_dir }}/bin/rake assets:precompile
  args:
    chdir: /home/{{ app_user }}/{{ app_dir }}
  register: precompile_assets_result
  environment:
    RAILS_ENV: production
  changed_when: "'Writing' in precompile_assets_result.stdout"
  notify:
  - restart frontend main service

- name: apply database migrations
  become: true
  become_user: "{{ app_user }}"
  command: /home/{{ app_user }}/{{ app_dir }}/bin/rake db:migrate
  args:
    chdir: /home/{{ app_user }}/{{ app_dir }}
  environment:
    RAILS_ENV: production
    DATABASE_URL: postgres:///{{ app_dir }}_production
  register: rake_db_migrate_result
  changed_when: "'migrating' in rake_db_migrate_result.stdout"
  notify:
  - restart frontend main service
  - restart frontend job queue service

- include: systemd.yml
- include: nginx.yml
