- name: copy server TLS key
  become: true
  become_user: seven_web
  copy:
    src: ../keys/{{ os_prefix }}/web_server.key.pem
    dest: /home/seven_web/keys/web.pem
    mode: 0640
  notify:
  - restart nginx daemon

- name: copy server TLS certificate
  become: true
  become_user: seven_web
  copy:
    src: ../keys/{{ os_prefix }}/web_server.cert.pem
    dest: /home/seven_web/keys/web.cer
    mode: 0644
  notify:
  - restart nginx daemon

- name: enable group access to seven_web home directory
  become: true
  become_user: root
  file: dest=/home/seven_web state=directory mode=750

- name: add nginx to seven_web group
  become: true
  become_user: root
  user: name=nginx groups=seven_web state=present append=true
  notify:
  - restart nginx daemon

- name: add nginx SElinux label to TLS files
  when: ansible_selinux != False
  become: true
  become_user: root
  file:
    dest: /home/seven_web/keys/{{ item }}
    state: file
    setype: httpd_sys_content_t
  with_items:
  - web.cer
  - web.pem

- name: add nginx SElinux label to seven_web assets
  when: ansible_selinux != False
  become: true
  become_user: root
  file:
    dest: /home/seven_web/seven/public
    state: directory
    setype: httpd_sys_content_t
    recurse: yes

- name: write nginx config
  become: true
  become_user: root
  template: src=nginx.conf.j2 dest=/etc/nginx/conf.d/seven_web.conf
  notify:
  - restart nginx daemon

- name: open HTTP and HTTPS in firewalld
  when: has_firewalld != False
  become: true
  become_user: root
  firewalld: service={{item}} state=enabled immediate=yes permanent=yes
  with_items:
  - http
  - https
