- name: create systemd unit for frontend main service
  become: true
  become_user: root
  template:
    src: main_systemd.service.j2
    dest: /lib/systemd/system/{{ app_main_service }}.service
  notify:
  - reload systemd configuration
  - restart frontend main service

- name: create systemd unit for frontend job queue service
  become: true
  become_user: root
  template:
    src: jobs_systemd.service.j2
    dest: /lib/systemd/system/{{ app_queue_service }}.service
  notify:
  - reload systemd configuration
  - restart frontend job queue service

- name: enable and start systemd units for frontend
  become: true
  become_user: root
  service: name={{ item }} enabled=yes state=started
  with_items:
  - "{{ app_main_service }}"
  - "{{ app_queue_service }}"
