- name: create systemd unit for frontend
  become: true
  become_user: root
  template:
    src: fe_systemd.service.j2
    dest: /lib/systemd/system/seven_web.service
  notify:
  - reload systemd configuration
  - restart frontend service

- name: create systemd unit for frontend delayed_job
  become: true
  become_user: root
  template:
    src: dj_systemd.service.j2
    dest: /lib/systemd/system/seven_dj.service
  notify:
  - reload systemd configuration
  - restart frontend delayed_job service

- name: enable and start systemd units for frontend
  become: true
  become_user: root
  service: name={{ item }} enabled=yes state=started
  with_items:
  - seven_web
  - seven_dj
