# Configuration file for the daemonz plugin.
#
# For documentation and examples, refer to the original template in
# vendor/daemonz/config_template.yml

---
:daemons: 
  # Daemon configurations placed here will be read as if they were in a file in
  # config/daemonz. This is less maintainable if you have more than one daemon.
    
# The base path for daemon binaries specified in binary, start_binary and
# stop_binary.
:root_path: <%= RAILS_ROOT %>

# Where daemonz should log - set to stdout, stderr, or rails.
:logger: stdout

# Set to true to completely disable daemonz, and not load any plugins.
:disabled: false

# daemonz is loaded every time the Rails framework is loaded. Sometimes
# (e.g. when performing migrations) daemons aren't required, so we shouldn't
# have to wait for the few seconds it takes to start / stop daemons.

# Daemons will not be started / stopped when the name of the binary that's
# loading Rails ($0) is one of the following.
:disabled_for: 
- 'rake'
- 'script/generate'
- 'script/destroy'
- 'script/plugin'

# Daemons will not be started for the following environments. 
:disabled_in:
- 'test'
