---
# Creates the image that the VMs will boot from.

- name: create tmp directory
  file: path=./tmp state=directory mode=0755

- name: create tmp/images directory
  file: path=./tmp/images state=directory mode=0755

- name: download {{ image_name }} VM image
  get_url:
    dest: ./tmp/images/{{ image_name }}.qcow2
    timeout: 3600
    url: "{{ cloud_image_url }}"

- name: register {{ image_name }} VM image
  os_image:
    name: "{{ image_name }}"
    container_format: bare
    disk_format: qcow2
    timeout: 3600
    filename: ./tmp/images/{{ image_name }}.qcow2
    cloud: "{{ os_cloud }}"
