---
# Defines the networks connecting the VMs.

- name: register security group
  os_security_group:
    name: "{{ security_group_name }}"
    description: SSH + HTTP(S) from Internet
    cloud: "{{ os_cloud }}"

- name: add public ports to security group
  os_security_group_rule:
    security_group: "{{ security_group_name }}"
    direction: ingress
    protocol: tcp
    remote_ip_prefix: 0.0.0.0/0
    port_range_min: "{{ item }}"
    port_range_max: "{{ item }}"
    cloud: "{{ os_cloud }}"
  with_items: ["22", "80", "443"]
