---
# Creates storage volumes and attaches them to each of the VMs.

- name: create master volume
  os_volume:
    display_name: "{{ master_volume_name }}"
    display_description:
      Backs the database on {{ master_instance_name }}
    size: "{{ os_master_volume_gb }}"
    volume_type: "{{ os_volume_type }}"
    cloud: "{{ os_cloud }}"

- name: create worker volumes
  os_volume:
    display_name: "{{ worker_volume_prefix }}{{ item }}"
    display_description:
      Stores Docker images and data for {{ worker_instance_prefix }}{{ item }}
    size: "{{ os_worker_volume_gb }}"
    volume_type: "{{ os_volume_type }}"
    cloud: "{{ os_cloud }}"
  with_sequence: start=1 end={{ worker_count }}

- name: attach master volume to VM
  os_server_volume:
    server: "{{ master_instance_name }}"
    device: /dev/vdb
    volume: "{{ master_volume_name }}"
    cloud: "{{ os_cloud }}"

- name: attach worker volumes to VMs
  os_server_volume:
    server: "{{ worker_instance_prefix }}{{ item }}"
    device: /dev/vdb
    volume: "{{ worker_volume_prefix }}{{ item }}"
    cloud: "{{ os_cloud }}"
  with_sequence: start=1 end={{ worker_count }}
