---
# Creates the storage volume holding the master VM's root filesystem.

- name: create master root volume
  os_volume:
    display_name: "{{ master_volume_name }}"
    display_description: "Root filesystem for {{ master_instance_name }}"
    image: "{{ image_name }}"
    size: "{{ os_master_volume_gb }}"
    volume_type: "{{ os_volume_type }}"
    # NOTE: Copying the image into the volume tends to take a while.
    timeout: 3600
    cloud: "{{ os_cloud }}"
