---
- name: update fedora server
  become: true
  become_user: root
  command: dnf upgrade -y
  register: dnf_update_result
  changed_when: "'Nothing to do.' not in dnf_update_result.stdout"
  notify:
  - reboot fedora server
  - wait for fedora server to come back up
  - reload facts after fedora upgrade

# NOTE: This makes sure that the machine reboots before it proceeds to the next
#       play.
- meta: flush_handlers
