---
# The name of the frontend application.
#
# This is used to derive several of the properties below.
app_name: seven

# The git repository that contains the frontend application.
app_git_repo: https://github.com/pwnall/seven.git

# The branch to be deployed from the application's git repository.
app_git_branch: master

# The name of the user account that contains the frontend application.
app_user: "{{ app_name }}_web"

# The name of the application's Postgres database.
app_db_name: "{{ app_name }}_production"

# The directory where the frontend application is checked out.
# This is a relative path inside the user's home directory.
app_dir: "{{ app_name }}"

# The name of the Systemd service used to run the application.
app_main_service: "{{ app_dir }}_web"

# The name of the Systemd service used to process the application's job queue.
app_queue_service: "{{ app_dir }}_dj"
