---
- name: check if /dev/vdb exists
  stat: path=/dev/vdb
  register: dev_vdb_stat

- name: write docker-storage-setup config
  become: true
  become_user: root
  when: dev_vdb_stat.stat.exists
  template:
    src: docker-storage-setup.j2
    dest: /etc/sysconfig/docker-storage-setup
  notify:
  - reconfigure Docker LVM storage
  - restart docker daemon
