require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RecitationSectionsController do

  # This should return the minimal set of attributes required to create a valid
  # RecitationSection. As you add validations to RecitationSection, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RecitationSectionsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all recitation_sections as @recitation_sections" do
      recitation_section = RecitationSection.create! valid_attributes
      get :index, {}, valid_session
      assigns(:recitation_sections).should eq([recitation_section])
    end
  end

  describe "GET show" do
    it "assigns the requested recitation_section as @recitation_section" do
      recitation_section = RecitationSection.create! valid_attributes
      get :show, {:id => recitation_section.to_param}, valid_session
      assigns(:recitation_section).should eq(recitation_section)
    end
  end

  describe "GET new" do
    it "assigns a new recitation_section as @recitation_section" do
      get :new, {}, valid_session
      assigns(:recitation_section).should be_a_new(RecitationSection)
    end
  end

  describe "GET edit" do
    it "assigns the requested recitation_section as @recitation_section" do
      recitation_section = RecitationSection.create! valid_attributes
      get :edit, {:id => recitation_section.to_param}, valid_session
      assigns(:recitation_section).should eq(recitation_section)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new RecitationSection" do
        expect {
          post :create, {:recitation_section => valid_attributes}, valid_session
        }.to change(RecitationSection, :count).by(1)
      end

      it "assigns a newly created recitation_section as @recitation_section" do
        post :create, {:recitation_section => valid_attributes}, valid_session
        assigns(:recitation_section).should be_a(RecitationSection)
        assigns(:recitation_section).should be_persisted
      end

      it "redirects to the created recitation_section" do
        post :create, {:recitation_section => valid_attributes}, valid_session
        response.should redirect_to(RecitationSection.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved recitation_section as @recitation_section" do
        # Trigger the behavior that occurs when invalid params are submitted
        RecitationSection.any_instance.stub(:save).and_return(false)
        post :create, {:recitation_section => {}}, valid_session
        assigns(:recitation_section).should be_a_new(RecitationSection)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        RecitationSection.any_instance.stub(:save).and_return(false)
        post :create, {:recitation_section => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested recitation_section" do
        recitation_section = RecitationSection.create! valid_attributes
        # Assuming there are no other recitation_sections in the database, this
        # specifies that the RecitationSection created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        RecitationSection.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => recitation_section.to_param, :recitation_section => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested recitation_section as @recitation_section" do
        recitation_section = RecitationSection.create! valid_attributes
        put :update, {:id => recitation_section.to_param, :recitation_section => valid_attributes}, valid_session
        assigns(:recitation_section).should eq(recitation_section)
      end

      it "redirects to the recitation_section" do
        recitation_section = RecitationSection.create! valid_attributes
        put :update, {:id => recitation_section.to_param, :recitation_section => valid_attributes}, valid_session
        response.should redirect_to(recitation_section)
      end
    end

    describe "with invalid params" do
      it "assigns the recitation_section as @recitation_section" do
        recitation_section = RecitationSection.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RecitationSection.any_instance.stub(:save).and_return(false)
        put :update, {:id => recitation_section.to_param, :recitation_section => {}}, valid_session
        assigns(:recitation_section).should eq(recitation_section)
      end

      it "re-renders the 'edit' template" do
        recitation_section = RecitationSection.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RecitationSection.any_instance.stub(:save).and_return(false)
        put :update, {:id => recitation_section.to_param, :recitation_section => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested recitation_section" do
      recitation_section = RecitationSection.create! valid_attributes
      expect {
        delete :destroy, {:id => recitation_section.to_param}, valid_session
      }.to change(RecitationSection, :count).by(-1)
    end

    it "redirects to the recitation_sections list" do
      recitation_section = RecitationSection.create! valid_attributes
      delete :destroy, {:id => recitation_section.to_param}, valid_session
      response.should redirect_to(recitation_sections_url)
    end
  end

end
