---
# Installs a specified Docker build, or the most recent Docker build in a
# specified Fedora branch.

- block:
  - name: install koji tools
    dnf: name=fedora-packager state=present

  - name: create koji_docker directory
    file: path=/root/koji_docker state=directory

  - name: get the latest docker version from {{ hax_docker_tag }}
    when: hax_docker_tag
    command: koji latest-build {{ hax_docker_tag }} docker --quiet
    register: koji_latest_docker_build_result
    changed_when: False

  - name: find the desired docker
    when: hax_docker_tag
    set_fact:
      # NOTE: The desired build name is the first word in the output.
      hax_docker_version: "{{ koji_latest_docker_build_result.stdout |
                              regex_replace(' .*\\Z', '') }}"

  - name: set the desired docker version to {{ hax_docker }}
    when: hax_docker
    set_fact:
      hax_docker_version: "{{ hax_docker }}"

  - name: create directory for the desired docker
    file: path=/root/koji_docker/{{ hax_docker_version }} state=directory

  - name: get docker from koji
    command: >
      koji download-build --quiet --arch={{ ansible_architecture }}
      {{ hax_docker_version }}
    args:
      chdir: /root/koji_docker/{{ hax_docker_version }}

  - name: list the downloaded docker packages
    find:
      paths: /root/koji_docker/{{ hax_docker_version }}
      patterns: "*.rpm"
    register: hax_docker_package_files

  - name: install the downloaded docker packages
    # NOTE: dnf doesn't appear to support package lists
    yum:
      name: "{{ hax_docker_package_files.files | map(attribute='path') |
                join(',') }}"
      state: present
  when: ansible_pkg_mgr == 'dnf' and (hax_docker or hax_docker_tag)
  become: true
  become_user: root
