---
# NOTE: This fixes some SElinux issues, such as the one documented below.
#       https://major.io/2015/09/18/systemd-in-fedora-22-failed-to-restart-service-access-denied/
- name: cast systemd reexec black magic
  become: true
  become_user: root
  command: systemctl daemon-reexec

- name: reboot machine
  become: true
  become_user: root
  command: systemctl reboot
  ignore_errors: true

- name: wait for machine to come back up
  # NOTE: ansible_ssh_port isn't always defined, per
  #       https://github.com/ansible/ansible/issues/13430#issuecomment-162105225
  local_action: >
    wait_for host={{ ansible_ssh_host }}
    port={{ hostvars[inventory_hostname].get('ansible_ssh_port', 22) }}
    search_regex=OpenSSH delay=10 timeout=600
  become: false

- name: reload facts after OS upgrade
  setup:
