---
# Installs Python 2 and the libraries needed by Ansible modules.

- name: install python 2.7 using apt
  become: true
  become_user: root
  raw: "if which apt-get; then apt-get install -y python-minimal; fi"

- name: install python 2.7 using dnf
  become: true
  become_user: root
  raw: "if which dnf; then dnf install -y python2 python-simplejson; fi"

- name: collect facts
  setup:

- name: install dnf-python
  when: ansible_pkg_mgr == 'dnf'
  become: true
  become_user: root
  command: dnf install -y python2-dnf
  # NOTE: By default, the command module will issue a warning suggesting the
  #       use of the dnf module. That's exactly what we want to do. However, we
  #       first need to install dnf-python for Ansible's dnf module.
  args:
    warn: no
  register: dnf_install_python_result
  changed_when: '"Nothing to do" not in dnf_install_python_result.stdout'

- name: install aptitude and python-apt
  when: ansible_pkg_mgr == 'apt'
  become: true
  become_user: root
  command: apt install -y aptitude python-apt
  # NOTE: By default, the command module will issue a warning suggesting the
  #       use of the apt module. That's exactly what we want to do. However, we
  #       first need to install python-apt for Ansible's python module.
  args:
    warn: no
  register: apt_install_python_result
  changed_when:
  - '"0 upgraded, 0 newly installed" not in apt_install_python_result.stdout'

- name: install dnf packages needed by ansible
  when: ansible_pkg_mgr == 'dnf'
  become: true
  become_user: root
  dnf: name={{ item }} state=present
  with_items:
  - libsemanage-python
  - libselinux-python
  - python-firewall
