# A background job to generate a recitation partition for a given course.
class RecitationAssignerJob < ApplicationJob
  queue_as :default

  # The recitation partition generated by the recitation assigner.
  attr_accessor :partition
  # The user who initiated this job.
  attr_accessor :requester
  # The root url.
  attr_accessor :root_url

  # Notify the requester via email of the completed partition.
  after_perform do |job|
    RecitationAssignmentMailer.recitation_assignment_email(
        requester.email, partition, root_url).deliver_now
  end

  # Generate a potential recitation partition for the given course.
  def perform(course, requester, root_url)
    self.partition = RecitationAssigner.new(course).partition!
    self.requester = requester
    self.root_url = root_url
  end
end
