---
- name: install docker with dnf
  when: ansible_pkg_mgr == 'dnf'
  become: true
  become_user: root
  dnf: name=docker state=present

- name: install docker with apt
  when: ansible_pkg_mgr == 'apt'
  become: true
  become_user: root
  apt: name=docker.io state=present

- name: create docker group
  become: true
  become_user: root
  group: name=docker system=yes state=present

# NOTE: Ubuntu does not mess with the docker group, so this step is not
#       necessary there.
- name: write docker config for fedora
  when: ansible_os_family == 'RedHat'
  become: true
  become_user: root
  template: src=docker_config.j2 dest=/etc/sysconfig/docker
  notify:
  - restart docker daemon

- name: enable and start docker daemon
  become: true
  become_user: root
  service: name=docker enabled=yes state=started
