---
# TODO(pwnall): phase out the docker repository in favor of Fedora's version
- name: install docker dnf repository
  when: ansible_pkg_mgr == 'dnf'
  become: true
  become_user: root
  template: src=docker_com.repo.j2 dest=/etc/yum.repos.d/docker_com.repo

- name: install docker with dnf
  when: ansible_pkg_mgr == 'dnf'
  become: true
  become_user: root
  # NOTE: The RedHat repositories package Docker as the "docker" package. The
  #       "docker-engine" package comes from the docker.com repositories.
  # dnf: name=docker state=present
  # TODO(pwnall): phase out docker-engine for Fedora's packaged version
  dnf: name=docker-engine state=present

- name: install docker with apt
  when: ansible_pkg_mgr == 'apt'
  become: true
  become_user: root
  apt: name=docker.io state=present

- name: create docker group
  become: true
  become_user: root
  group: name=docker system=yes state=present

- name:  create docker systemd drop-in directory
  become: true
  become_user: root
  file: path=/etc/systemd/system/docker.service.d state=directory mode=0755

- name: write docker systemd drop-in for Fedora config compatibility
  become: true
  become_user: root
  # NOTE: Template inspired by
  #       http://docs.docker.com/engine/articles/systemd/#custom-docker-daemon-options
  template:
    src: systemd_fedora_config.conf.j2
    dest: /etc/systemd/system/docker.service.d/10-fedora-config.conf
  register: docker_systemd_fedora_config_dropin
  notify:
  - restart docker daemon

- name: reload systemd configuration
  command: systemctl daemon-reload
  become: true
  become_user: root
  when: docker_systemd_fedora_config_dropin | changed

- name:  create /etc/sysconfig directory
  become: true
  become_user: root
  file: path=/etc/systemd/system/docker.service.d state=directory mode=0755

- name: write docker config
  become: true
  become_user: root
  template: src=sysconfig_docker.j2 dest=/etc/sysconfig/docker
  notify:
  - restart docker daemon

- name: enable and start docker socket and daemon
  become: true
  become_user: root
  service: name=docker enabled=yes state=started
