---
# Installs and configures the Docker daemon.

- include: packages.yml

- name: create docker group
  become: true
  become_user: root
  group: name=docker system=yes state=present

- name:  create docker systemd drop-in directory
  become: true
  become_user: root
  file: path=/etc/systemd/system/docker.service.d state=directory mode=0755

- name: write docker systemd drop-in for Fedora config compatibility
  become: true
  become_user: root
  # NOTE: Template inspired by
  #       http://docs.docker.com/engine/articles/systemd/#custom-docker-daemon-options
  template:
    src: systemd_fedora_config.conf.j2
    dest: /etc/systemd/system/docker.service.d/10-fedora-config.conf
  register: docker_systemd_fedora_config_dropin
  notify:
  - restart docker daemon

- name: reload systemd configuration
  command: systemctl daemon-reload
  become: true
  become_user: root
  when: docker_systemd_fedora_config_dropin | changed

- name:  create /etc/sysconfig directory
  become: true
  become_user: root
  file: path=/etc/sysconfig state=directory mode=0755

- name: write docker config
  become: true
  become_user: root
  template: src=sysconfig_docker.j2 dest=/etc/sysconfig/docker
  notify:
  - restart docker daemon

# TODO(pwnall): Remove this hack when the PR below gets into a release.
#               https://github.com/docker/docker/pull/28733
- name: set SELinux to permissive
  when: ansible_selinux != False
  become: true
  become_user: root
  selinux: policy=targeted state=permissive

- name: enable and start docker socket and daemon
  become: true
  become_user: root
  service: name=docker enabled=yes state=started
