---
- name: install docker apt key
  when: ansible_pkg_mgr == 'apt'
  become: true
  become_user: root
  apt_key:
    keyserver: hkp://p80.pool.sks-keyservers.net:80
    id: 58118E89F3A912897C070ADBF76221572C52609D

- name: install docker apt repository
  when: ansible_pkg_mgr == 'apt'
  become: true
  become_user: root
  apt_repository:
    repo: "deb https://apt.dockerproject.org/repo
           {{ ansible_distribution|lower }}-{{ ansible_distribution_release }}
           {{ docker_engine_branch }}"
    state: present
    filename: docker
    update_cache: yes
    validate_certs: yes

- name: install docker with dnf
  when: ansible_pkg_mgr == 'dnf'
  become: true
  become_user: root
  dnf: name=docker state=present

- name: install docker with apt
  when: ansible_pkg_mgr == 'apt'
  become: true
  become_user: root
  apt: name=docker-engine state=present
